version: '3'
services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - my-network

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: finance
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    networks:
      - my-network
  
  auth-api:
    container_name: auth-api
    build:
      context: ./backend/api/auth-api
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app/backend
    networks:
      - my-network

networks:
  my-network: