name: Continuous Delivery
on:
    pull_request:
      branches: [ "main" ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Login no Docker Hub
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            - name: Build docker image auth-api
              run: cd backend/api/auth-api && docker build -t thiagosantos007/auth-api .
            - name: Push image auth-api
              run: docker push thiagosantos007/auth-api
            - name: Build docker image accounts-api
              run: cd backend/api/accounts-api && docker build -t thiagosantos007/accounts-api .
            - name: Push image accounts-api
              run: docker push thiagosantos007/accounts-api
            - name: Build docker image frontend
              run: cd frontend && docker build -t thiagosantos007/frontend .
            - name: Push image frontend
              run: docker push thiagosantos007/frontend
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull da image from Docker Hub auth-api 
              run: docker pull thiagosantos007/auth-api:latest

            - name: Remove Docker container auth-api
              run: docker rm -f auth-api

            - name: Run Docker continer auth-api
              run: docker run -d -p 3001:3001 -e AUTH_SECRET=${{secrets.AUTH_SECRET}} -e POSTGRES_USER=${{secrets.POSTGRES_USER}} -e POSTGRES_HOST=${{secrets.POSTGRES_HOST}} -e POSTGRES_PORT=${{secrets.POSTGRES_PORT}} -e POSTGRES_PASS=${{secrets.POSTGRES_PASS}} -e POSTGRES_DATABASE=${{secrets.POSTGRES_DATABASE}} --name auth-api thiagosantos007/auth-api

            - name: Pull da image from Docker Hub accounts-api 
              run: docker pull thiagosantos007/accounts-api:latest

            - name: Remove Docker container accounts-api
              run: docker rm -f accounts-api

            - name: Run Docker continer accounts-api
              run: docker run -d -p 3002:3002 -e AUTH_SECRET=${{secrets.AUTH_SECRET}} -e POSTGRES_USER=${{secrets.POSTGRES_USER}} -e POSTGRES_HOST=${{secrets.POSTGRES_HOST}} -e POSTGRES_PORT=${{secrets.POSTGRES_PORT}} -e POSTGRES_PASS=${{secrets.POSTGRES_PASS}} -e POSTGRES_DATABASE=${{secrets.POSTGRES_DATABASE}} --name accounts-api thiagosantos007/accounts-api

            - name: Pull da image from Docker Hub frontend
              run: docker pull thiagosantos007/frontend:latest

            - name: Remove Docker container frontend
              run: docker rm -f frontend

            - name: Run Docker continer frontend
              run: docker run -d -p 3000:3000 --name frontend thiagosantos007/frontend