name: Continuous Integration 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Buildando a API Auth
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd backend/api/auth-api && npm i && npm test
    - name: Buildando a API Accounts
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd backend/api/accounts-api && npm i && npm test
    - name: Buildando o FrontEnd
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd frontend && npm i && npm run build
